-- Your SQL goes here
CREATE TABLE users(
	id			INT 	UNSIGNED	AUTO_INCREMENT,
	nickname	TEXT	UNIQUE		NOT NULL,
	password	TEXT				NOT NULL,
	email		TEXT				NOT NULL,
	admin		BOOLEAN	DEFAULT(0)	NOT NULL,
	PRIMARY KEY (`id`)
);

CREATE TABLE tokens(
	id			INT		UNSIGNED	AUTO_INCREMENT,
	user_id		INT		UNSIGNED	NOT NULL,
	token		TEXT				NOT NULL,
	PRIMARY KEY (`id`)
);
